# Questions 1

In [1]:
import numpy as np
arr=np.array(range(2,50,3))
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Questions 2

In [2]:
lst1 = []
lst2=[]
n = int(input("Enter 5 elements without space : ")) 
for i in range(0,5): 
    lst1.append(int(i))
n = int(input("Enter 5 elements without space : ")) 
for j in range(0,5): 
    lst2.append(int(j))      
arr1=np.array(lst1)
arr2=np.array(lst2)
concat_arr=np.concatenate([arr1,arr2])
sort_arr=np.sort(concat_arr)
print("Concatenate Array ",concat_arr)
print("Sort Array ",sort_arr)

Enter 5 elements without space : 12345
Enter 5 elements without space : 23456
Concatenate Array  [0 1 2 3 4 0 1 2 3 4]
Sort Array  [0 0 1 1 2 2 3 3 4 4]


# Questions 3

In [ ]:
a = np.array([[[1,2,3],[1,2,3]],[[12,3,4],[2,1,3]]])
print("dimensions = ",len(a.shape))
print(a.size)

# Questions 4

In [18]:
lis=[1,9,3,9,4,1,3,5,8,2,3,10]
one_d=np.array(lis)
two_d=one_d.reshape(3,4)
print(len(two_d.shape))

2


# Questions 5

In [25]:
a = np.array([[9,25,4],[49,9,36]])
b = np.array([[4,9,81],[4,16,64]])
print(np.vstack((a, b)))
print(np.hstack((a,b)))

[[ 9 25  4]
 [49  9 36]
 [ 4  9 81]
 [ 4 16 64]]
[[ 9 25  4  4  9 81]
 [49  9 36  4 16 64]]


# Questions 6

In [24]:
lis= np.array([1, 1, 2, 3, 4, 4, 1])
(unique,counts)=np.unique(lis,return_counts=True)
frequencies = np.asarray((unique, counts)).T
print(frequencies)

[[1 3]
 [2 1]
 [3 1]
 [4 2]]
